openapi: 3.0.0

info:
    title: MDE exclusion plugin
    description: API plugin skills to retrieve threat indicators from Microsoft Defender for Endpoint.
    version: "v1.4"

servers:
#   - url: https://us.api.security.microsoft.com/api
   - url: https://
   
paths:
##################################################################################################################
# List Indicators API
#  https://learn.microsoft.com/en-us/defender-endpoint/api/get-ti-indicators-collection
##################################################################################################################

  us.api.security.microsoft.com/api/indicators:
#  /indicators:
    get:
      operationId: MDE-test
      description: Searches the MDE threat indicators exclusion description field.
      descriptionForModel: Searches the MDE threat indicators exclusion description field.
      examplePrompts: test
      responses:
        "200":
          description: Successful response with a list of threat indicators.
          content:
            application/json:
              schema:
                type: object
                properties:
                  "@odata.context":
                    type: string
                    example: "https://api.securitycenter.microsoft.com/api/$metadata#Indicators"
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "995"
                        indicatorValue:
                          type: string
                          example: "12.13.14.15"
                        indicatorType:
                          type: string
                          enum: [IpAddress, FileSha1, FileSha256, Domain, Url]
                          example: "IpAddress"
                        action:
                          type: string
                          enum: [Alert, AlertAndBlock, Allow, Block]
                          example: "Alert"
                        application:
                          type: string
                          nullable: true
                          example: "demo-test"
                        source:
                          type: string
                          example: "TestPrdApp"
                        sourceType:
                          type: string
                          example: "AadApp"
                        title:
                          type: string
                          example: "test"
                        creationTimeDateTimeUtc:
                          type: string
                          format: date-time
                          example: "2018-10-24T11:15:35.3688259Z"
                        createdBy:
                          type: string
                          example: "45097602-1234-5678-1234-9f453233e62c"
                        expirationTime:
                          type: string
                          format: date-time
                          example: "2020-12-12T00:00:00Z"
                        lastUpdateTime:
                          type: string
                          format: date-time
                          example: "2019-10-24T10:54:23.2009016Z"
                        lastUpdatedBy:
                          type: string
                          example: "TestPrdApp"
                        severity:
                          type: string
                          enum: [Informational, Low, Medium, High]
                          example: "Informational"
                        description:
                          type: string
                          example: "test"
                        recommendedActions:
                          type: string
                          example: "test"
                        rbacGroupNames:
                          type: array
                          items:
                            type: string
                          example: []
        "401":
          description: Unauthorized - Invalid or missing authentication token.
        "403":
          description: Forbidden - Insufficient permissions.
        "500":
          description: Internal Server Error.

#################################################################################

  graph.microsoft.com/v1.0/me:
#  /indicators:
    get:
      operationId: MDE-test-2
      description: get profile info
      responses:
        "200":
          description: Successful response with a list of threat indicators.

          
#################################################################################
# https://us.api.security.microsoft.com/api/indicators?$filter=contains(tolower(description), 'Demo')

  us.api.security.microsoft.com/api/indicators?$filter=contains(tolower(description), '{searchQuery}'):
#  /indicators?$filter=contains(tolower(description), '{searchQuery}'):
    get:
      operationId: MDE-ExclusionSearchDescription
      description: Searches the MDE threat indicators exclusion description field.
      descriptionForModel: Searches the MDE threat indicators exclusion description field.
      examplePrompts: test
      parameters:
        - name: searchQuery
          in: path
          required: true
          description: String to search for in the MDE exclusion description field
#         placeholderValue: test
#         defaultValue: demo
          schema:
            type: string
            example: "demo"
      responses:
        "200":
          description: Successful response with a list of threat indicators.
          content:
            application/json:
              schema:
                type: object
                properties:
                  "@odata.context":
                    type: string
                    example: "https://api.securitycenter.microsoft.com/api/$metadata#Indicators"
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "995"
                        indicatorValue:
                          type: string
                          example: "12.13.14.15"
                        indicatorType:
                          type: string
                          enum: [IpAddress, FileSha1, FileSha256, Domain, Url]
                          example: "IpAddress"
                        action:
                          type: string
                          enum: [Alert, AlertAndBlock, Allow, Block]
                          example: "Alert"
                        application:
                          type: string
                          nullable: true
                          example: "demo-test"
                        source:
                          type: string
                          example: "TestPrdApp"
                        sourceType:
                          type: string
                          example: "AadApp"
                        title:
                          type: string
                          example: "test"
                        creationTimeDateTimeUtc:
                          type: string
                          format: date-time
                          example: "2018-10-24T11:15:35.3688259Z"
                        createdBy:
                          type: string
                          example: "45097602-1234-5678-1234-9f453233e62c"
                        expirationTime:
                          type: string
                          format: date-time
                          example: "2020-12-12T00:00:00Z"
                        lastUpdateTime:
                          type: string
                          format: date-time
                          example: "2019-10-24T10:54:23.2009016Z"
                        lastUpdatedBy:
                          type: string
                          example: "TestPrdApp"
                        severity:
                          type: string
                          enum: [Informational, Low, Medium, High]
                          example: "Informational"
                        description:
                          type: string
                          example: "test"
                        recommendedActions:
                          type: string
                          example: "test"
                        rbacGroupNames:
                          type: array
                          items:
                            type: string
                          example: []
        "401":
          description: Unauthorized - Invalid or missing authentication token.
        "403":
          description: Forbidden - Insufficient permissions.
        "500":
          description: Internal Server Error.
