openapi: 3.0.0

info:
  title: httpbin.org
  description: A simple HTTP Request & Response Service.
  version: "0.9.7"

servers:
  - url: https://httpbin.org/
     
paths:
    /headers:
      get: 
        operationId: TestApiKeyAuth
        summary: Returns the provided headers
        parameters:
          - in: header
            name: x-xdr-auth-id
            required: false
            description: my API auth ID
            schema:
              type: string
              default: 1234            # API authentication ID to be passed during each request
        responses:
          "200":
            description: OK
          "400":
            description: Bad request, invalid parameters

components:
  securitySchemes:
    apiKeyIDAuth:              # Arbitrary name for the security scheme
      type: apiKey
      in: header               # Can be "header", "query" or "cookie"
      name: x-xdr-auth-id      # Value sent to the endpoint in the requested (e.g. {x-xdr-auth-id: 24})
      description: "The API Key ID for authentication."
    apiKeySecretAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "The API Key Secret for authentication."
  security:
    - apiKeyIDAuth: []
      apiKeySecretAuth: []   # <-- No leading dash (-) as this indicates both must be present and NOT either or.
