openapi: 3.0.0

info:
    title: httpbin.org
    description: A simple HTTP Request & Response Service.
    version: "0.9.2"

servers:
    - url: https://httpbin.org/

components:
  securitySchemes:
    apiKeyIDAuth:              # arbitrary name for the security scheme
      type: apiKey
      in: header               # can be "header", "query" or "cookie"
      name: x-xdr-auth-id      # Value sent to the endpoint in the requested (e.g. {x-xdr-auth-id: 24})
      description: "The API Key ID for authentication."
    apiKeySecretAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "The API Key Secret for authentication."
      
paths:
    /headers:
        get: 
            operationId: TestApiKeyAuth
            summary: Returns the provided headers
            responses:
                200:
                    description: Successful request.
