openapi: 3.0.0

info:
    title: httpbin.org
    description: A simple HTTP Request & Response Service.
    version: "0.9.2"

servers:
    - url: https://httpbin.org/
     
paths:
    /headers:
        get: 
            operationId: TestApiKeyAuth
            summary: Returns the provided headers
            parameters:
              - name: x-xdr-auth-id
                in: header
                required: false
                description: my API auth ID
                schema:
                  type: string
                  default: 24
            responses:
                200:
                  description: Successful request.
