# Author Rick Kotlarz - https://github.com/RickKotlarz/
# Plugin updated 2025-Jan-08

openapi: 3.0.0

info:
  title: httpbin.org-amit
  description: A simple HTTP Request & Response Service.-amit
  descriptionForModel: A simple HTTP Request & Response Service.-amit
  # descriptionForModel: A verbose and detailed description to help the model select this skil over other skills.
  version: "0.9.16"

servers:
  - url: https://httpbin.org/
     
paths:
  /headers:
    get:
      operationId: TestApiKeyAuth
      summary: Returns the provided headers
      parameters:
        - $ref: '#/components/parameters/x-xdr-auth-id'
        # The above parameter inserts the 'x-xdr-auth-id' and default value into the header when the 'TestApiKeyAuth' is executed by the user.
      responses:
        "200":
          description: OK
        "400":
          description: Bad request, invalid parameters

  /anything:
    post:
      summary: Remediate analyzed emails
      description: Triggers remediation actions on analyzed emails identified as threats.
      operationId: remediateAnalyzedEmails
      descriptionForModel: This operation triggers remediation actions on analyzed emails identified as threats by accepting a list of message IDs and a specified remediation action, enabling automated threat response workflows in Microsoft Defender Action Center.
      examplePrompts:
        - Remediate emails with IDs "abc123" and "xyz789" by moving them to Junk.
        - Trigger a soft delete on analyzed emails identified as threats with message IDs "msg001", "msg002".
        - Move emails "email1", "email2", and "email3" to Deleted Items due to user report.
        - Remediate analyzed email "threat123" with a hard delete and add reason "detectedThreat".
        - Take action on emails "spam001" and "spam002" by moving them to Inbox with tag "falsePositive".
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemediateRequest'
      responses:
        '204':
          description: Success - No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error



components:
  parameters:
    x-xdr-auth-id:
      name: x-xdr-auth-id
      in: header
      required: false
      description: "My API auth ID"
      schema:
        type: string
        default: 1234          # API authentication ID to be passed during each request. DO NOT encapsulate the value in quotes.
#       default: {{settingTestName}}
  securitySchemes:
    apiKeyIDAuth:              # Arbitrary name for the security scheme
      type: apiKey
      in: header               # Can be "header", "query" or "cookie"
      name: x-xdr-auth-id      # Value sent to the endpoint in the requested (e.g. {x-xdr-auth-id: 24})
      description: "The API Key ID for authentication."
    apiKeySecretAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "The API Key Secret for authentication."
  security:
    - apiKeyIDAuth: []
      apiKeySecretAuth: []   # <-- No leading dash (-) as this indicates both must be present and NOT either OR.
  schemas:
    RemediateRequest:
      type: object
      required:
        - messageIds
        - remediationAction
      properties:
        messageIds:
          type: array
          items:
            type: string
          description: Collection of IDs of the messages to remediate.
        remediationAction:
          type: string
          enum:
            - moveToInbox
            - moveToJunk
            - moveToDeletedItems
            - softDelete
            - hardDelete
          description: The action to take on the messages.
        customActionReason:
          type: string
          description: Optional reason for choosing the action.
        reason:
          type: string
          enum:
            - userReported
            - detectedThreat
            - other
          description: The justification for the remediation action.
        tags:
          type: array
          items:
            type: string
          description: Optional tags for the remediation action.