openapi: 3.0.1

info:
  title: Microsoft Graph API - Devices
  description: API plugin to interact with devices in Microsoft Entra (Azure AD)
  version: 1.0.0
  
servers:
  - url: https://graph.microsoft.com/v1.0
  
paths:
  /devices:
    get:
      summary: Get all devices with a filter on last sign-in date
      description: Retrieve a list of devices where the last sign-in date is beyond 90 days.
      operationId: getDevices
      parameters:
        - name: $filter
          in: query
          required: true
          schema:
            type: string
            example: "approximateLastSignInDateTime le 2025-01-21"
            description: OData filter to retrieve devices with a last sign-in date greater than 90 days ago.
      responses:
        '200':
          description: A list of devices filtered by last sign-in date
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier for the device
                        displayName:
                          type: string
                          description: The name of the device
                        approximateLastSignInDateTime:
                          type: string
                          format: date-time
                          description: The last sign-in date of the device
                        deviceId:
                          type: string
                          description: The device ID
                example:
                  value:
                    - id: "device1-id"
                      displayName: "Device 1"
                      approximateLastSignInDateTime: "2024-12-01T12:00:00Z"
                      deviceId: "device1"
                    - id: "device2-id"
                      displayName: "Device 2"
                      approximateLastSignInDateTime: "2024-11-10T12:00:00Z"
                      deviceId: "device2"
        '401':
          description: Unauthorized. Missing or invalid authentication token.
        '403':
          description: Forbidden. The authenticated user does not have permission to access the devices.
        '500':
          description: Internal Server Error. A server-side error occurred while processing the request.
